package com.hotels.project.common;

public enum EntityMetadata {
	ITEM_FRAGILE, ITEM_GIFT, ITEM_HEAVY, ITEM_MEDICINE, ITEM_GROCERRY,

	CATEGORY_GENERAL, CATEGORY_MEDICINE, CATEGORY_KIDS, CATEGORY_GIFT, CATEGORY_HEAVYWEIGHT, CATEGORY_NEW_ARRIAVEL,

	TAX_SALES, TAX_GST,

	FACTORY_CATEGORY, FACTORY_ITEM, FACTORY_TAX,

	UNKNOWN

}
